# Generated by Django 5.0.1 on 2024-02-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_average_rating_product_total_ratings_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
